# Generated by Django 3.2.22 on 2023-11-02 09:40

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default='../default_post_mhjm11', force_format='WEBP', keep_meta=True, quality=75, scale=None, size=[1920, 1080], upload_to='images/'),
        ),
    ]
