# Generated by Django 3.2.22 on 2023-11-02 10:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('condition', models.CharField(choices=[('new', 'New'), ('nearly_new', 'Nearly New'), ('used', 'Used')], default='new', max_length=50)),
                ('description', models.CharField(max_length=10000)),
                ('price', models.FloatField()),
                ('location', models.CharField(max_length=255)),
                ('image', django_resized.forms.ResizedImageField(crop=None, default='../default_post_mhjm11', force_format='WEBP', keep_meta=True, quality=75, scale=None, size=[400, None], upload_to='images/')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
